version: 2
updates:
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      interval: monthly
      time: '04:00'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'webpack'
      - dependency-name: 'sass'
      - dependency-name: 'lint-staged'
      - dependency-name: 'husky'
      - dependency-name: 'eslint'
      - dependency-name: 'cspell'
      - dependency-name: 'eslint'
      - dependency-name: '@babel/core'
      - dependency-name: '@babel/runtime'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
